# Generated by Django 5.1 on 2024-09-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('reference_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
