# Generated by Django 5.1 on 2024-09-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='Author',
            field=models.CharField(default='Unknown Author', max_length=50),
        ),
        migrations.AddField(
            model_name='reader',
            name='published',
            field=models.TextField(default='Unknown Date'),
        ),
    ]
