# Generated by Django 5.1 on 2024-10-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0004_reader_author_reader_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='password',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
