# Generated by Django 5.1 on 2024-10-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0005_library_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='reference_id',
            field=models.CharField(max_length=100),
        ),
    ]
